require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlimentsController do

  # This should return the minimal set of attributes required to create a valid
  # Aliment. As you add validations to Aliment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlimentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all aliments as @aliments" do
      aliment = Aliment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aliments).should eq([aliment])
    end
  end

  describe "GET show" do
    it "assigns the requested aliment as @aliment" do
      aliment = Aliment.create! valid_attributes
      get :show, {:id => aliment.to_param}, valid_session
      assigns(:aliment).should eq(aliment)
    end
  end

  describe "GET new" do
    it "assigns a new aliment as @aliment" do
      get :new, {}, valid_session
      assigns(:aliment).should be_a_new(Aliment)
    end
  end

  describe "GET edit" do
    it "assigns the requested aliment as @aliment" do
      aliment = Aliment.create! valid_attributes
      get :edit, {:id => aliment.to_param}, valid_session
      assigns(:aliment).should eq(aliment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Aliment" do
        expect {
          post :create, {:aliment => valid_attributes}, valid_session
        }.to change(Aliment, :count).by(1)
      end

      it "assigns a newly created aliment as @aliment" do
        post :create, {:aliment => valid_attributes}, valid_session
        assigns(:aliment).should be_a(Aliment)
        assigns(:aliment).should be_persisted
      end

      it "redirects to the created aliment" do
        post :create, {:aliment => valid_attributes}, valid_session
        response.should redirect_to(Aliment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aliment as @aliment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aliment.any_instance.stub(:save).and_return(false)
        post :create, {:aliment => { "name" => "invalid value" }}, valid_session
        assigns(:aliment).should be_a_new(Aliment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Aliment.any_instance.stub(:save).and_return(false)
        post :create, {:aliment => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aliment" do
        aliment = Aliment.create! valid_attributes
        # Assuming there are no other aliments in the database, this
        # specifies that the Aliment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Aliment.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => aliment.to_param, :aliment => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested aliment as @aliment" do
        aliment = Aliment.create! valid_attributes
        put :update, {:id => aliment.to_param, :aliment => valid_attributes}, valid_session
        assigns(:aliment).should eq(aliment)
      end

      it "redirects to the aliment" do
        aliment = Aliment.create! valid_attributes
        put :update, {:id => aliment.to_param, :aliment => valid_attributes}, valid_session
        response.should redirect_to(aliment)
      end
    end

    describe "with invalid params" do
      it "assigns the aliment as @aliment" do
        aliment = Aliment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aliment.any_instance.stub(:save).and_return(false)
        put :update, {:id => aliment.to_param, :aliment => { "name" => "invalid value" }}, valid_session
        assigns(:aliment).should eq(aliment)
      end

      it "re-renders the 'edit' template" do
        aliment = Aliment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Aliment.any_instance.stub(:save).and_return(false)
        put :update, {:id => aliment.to_param, :aliment => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aliment" do
      aliment = Aliment.create! valid_attributes
      expect {
        delete :destroy, {:id => aliment.to_param}, valid_session
      }.to change(Aliment, :count).by(-1)
    end

    it "redirects to the aliments list" do
      aliment = Aliment.create! valid_attributes
      delete :destroy, {:id => aliment.to_param}, valid_session
      response.should redirect_to(aliments_url)
    end
  end

end
