require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PeseesController do

  # This should return the minimal set of attributes required to create a valid
  # Pesee. As you add validations to Pesee, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "when" => "2012-12-29" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PeseesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pesees as @pesees" do
      pesee = Pesee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pesees).should eq([pesee])
    end
  end

  describe "GET show" do
    it "assigns the requested pesee as @pesee" do
      pesee = Pesee.create! valid_attributes
      get :show, {:id => pesee.to_param}, valid_session
      assigns(:pesee).should eq(pesee)
    end
  end

  describe "GET new" do
    it "assigns a new pesee as @pesee" do
      get :new, {}, valid_session
      assigns(:pesee).should be_a_new(Pesee)
    end
  end

  describe "GET edit" do
    it "assigns the requested pesee as @pesee" do
      pesee = Pesee.create! valid_attributes
      get :edit, {:id => pesee.to_param}, valid_session
      assigns(:pesee).should eq(pesee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pesee" do
        expect {
          post :create, {:pesee => valid_attributes}, valid_session
        }.to change(Pesee, :count).by(1)
      end

      it "assigns a newly created pesee as @pesee" do
        post :create, {:pesee => valid_attributes}, valid_session
        assigns(:pesee).should be_a(Pesee)
        assigns(:pesee).should be_persisted
      end

      it "redirects to the created pesee" do
        post :create, {:pesee => valid_attributes}, valid_session
        response.should redirect_to(Pesee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pesee as @pesee" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pesee.any_instance.stub(:save).and_return(false)
        post :create, {:pesee => { "when" => "invalid value" }}, valid_session
        assigns(:pesee).should be_a_new(Pesee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pesee.any_instance.stub(:save).and_return(false)
        post :create, {:pesee => { "when" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pesee" do
        pesee = Pesee.create! valid_attributes
        # Assuming there are no other pesees in the database, this
        # specifies that the Pesee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pesee.any_instance.should_receive(:update_attributes).with({ "when" => "2012-12-29" })
        put :update, {:id => pesee.to_param, :pesee => { "when" => "2012-12-29" }}, valid_session
      end

      it "assigns the requested pesee as @pesee" do
        pesee = Pesee.create! valid_attributes
        put :update, {:id => pesee.to_param, :pesee => valid_attributes}, valid_session
        assigns(:pesee).should eq(pesee)
      end

      it "redirects to the pesee" do
        pesee = Pesee.create! valid_attributes
        put :update, {:id => pesee.to_param, :pesee => valid_attributes}, valid_session
        response.should redirect_to(pesee)
      end
    end

    describe "with invalid params" do
      it "assigns the pesee as @pesee" do
        pesee = Pesee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pesee.any_instance.stub(:save).and_return(false)
        put :update, {:id => pesee.to_param, :pesee => { "when" => "invalid value" }}, valid_session
        assigns(:pesee).should eq(pesee)
      end

      it "re-renders the 'edit' template" do
        pesee = Pesee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pesee.any_instance.stub(:save).and_return(false)
        put :update, {:id => pesee.to_param, :pesee => { "when" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pesee" do
      pesee = Pesee.create! valid_attributes
      expect {
        delete :destroy, {:id => pesee.to_param}, valid_session
      }.to change(Pesee, :count).by(-1)
    end

    it "redirects to the pesees list" do
      pesee = Pesee.create! valid_attributes
      delete :destroy, {:id => pesee.to_param}, valid_session
      response.should redirect_to(pesees_url)
    end
  end

end
