require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UnitesController do

  # This should return the minimal set of attributes required to create a valid
  # Unite. As you add validations to Unite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UnitesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all unites as @unites" do
      unite = Unite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:unites).should eq([unite])
    end
  end

  describe "GET show" do
    it "assigns the requested unite as @unite" do
      unite = Unite.create! valid_attributes
      get :show, {:id => unite.to_param}, valid_session
      assigns(:unite).should eq(unite)
    end
  end

  describe "GET new" do
    it "assigns a new unite as @unite" do
      get :new, {}, valid_session
      assigns(:unite).should be_a_new(Unite)
    end
  end

  describe "GET edit" do
    it "assigns the requested unite as @unite" do
      unite = Unite.create! valid_attributes
      get :edit, {:id => unite.to_param}, valid_session
      assigns(:unite).should eq(unite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Unite" do
        expect {
          post :create, {:unite => valid_attributes}, valid_session
        }.to change(Unite, :count).by(1)
      end

      it "assigns a newly created unite as @unite" do
        post :create, {:unite => valid_attributes}, valid_session
        assigns(:unite).should be_a(Unite)
        assigns(:unite).should be_persisted
      end

      it "redirects to the created unite" do
        post :create, {:unite => valid_attributes}, valid_session
        response.should redirect_to(Unite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved unite as @unite" do
        # Trigger the behavior that occurs when invalid params are submitted
        Unite.any_instance.stub(:save).and_return(false)
        post :create, {:unite => { "name" => "invalid value" }}, valid_session
        assigns(:unite).should be_a_new(Unite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Unite.any_instance.stub(:save).and_return(false)
        post :create, {:unite => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested unite" do
        unite = Unite.create! valid_attributes
        # Assuming there are no other unites in the database, this
        # specifies that the Unite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Unite.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => unite.to_param, :unite => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested unite as @unite" do
        unite = Unite.create! valid_attributes
        put :update, {:id => unite.to_param, :unite => valid_attributes}, valid_session
        assigns(:unite).should eq(unite)
      end

      it "redirects to the unite" do
        unite = Unite.create! valid_attributes
        put :update, {:id => unite.to_param, :unite => valid_attributes}, valid_session
        response.should redirect_to(unite)
      end
    end

    describe "with invalid params" do
      it "assigns the unite as @unite" do
        unite = Unite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Unite.any_instance.stub(:save).and_return(false)
        put :update, {:id => unite.to_param, :unite => { "name" => "invalid value" }}, valid_session
        assigns(:unite).should eq(unite)
      end

      it "re-renders the 'edit' template" do
        unite = Unite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Unite.any_instance.stub(:save).and_return(false)
        put :update, {:id => unite.to_param, :unite => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested unite" do
      unite = Unite.create! valid_attributes
      expect {
        delete :destroy, {:id => unite.to_param}, valid_session
      }.to change(Unite, :count).by(-1)
    end

    it "redirects to the unites list" do
      unite = Unite.create! valid_attributes
      delete :destroy, {:id => unite.to_param}, valid_session
      response.should redirect_to(unites_url)
    end
  end

end
